/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Zambur (https://sketchfab.com/Zambur)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/crystal-ba43c7bbcca143c8ad2f77f5841b39de
title: Crystal
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas, useThree, useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('../../../../crystal/scene.gltf');
  useFrame((state, delta) => (group.current.rotation.y += 0.005));
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.pPlatonic1_lambert1_0.geometry}
            material={materials.lambert1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('../../../../crystal/scene.gltf');
